services:
    postgres:
        container_name: postgres
        image: postgres:12.2-alpine
        environment:
            - POSTGRES_DB=nakama
            - POSTGRES_PASSWORD=localdb
        volumes:
            - data:/var/lib/postgresql/data
        expose:
            - "8080"
            - "5432"
        ports:
            - "5432:5432"
            - "8080:8080"
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "nakama" ]
            interval: 3s
            timeout: 3s
            retries: 5
    nakama:
        build: .
        restart: always
        links:
            - "postgres:db"
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - ./logfile.log:/nakama/data/logfile.log
        expose:
            - "7349"
            - "7350"
            - "7351"
        ports:
            - "7349:7349"
            - "7350:7350"
            - "7351:7351"
        healthcheck:
            test: [ "CMD", "/nakama/nakama", "healthcheck" ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    data:
